## Promise的链式调用

```js
  const p = new Promise((reslove, reject) => {
    reslove('OK')
  })
  p.then((value) => {
    return Promise.resolve('TRUE');
  }).then((value) => {
    console.log(value); // TRUE
  }).then((value) => {
    console.log(value); // undefied
  })
  /*
    因为then方法返回的结果为一个promise，所以可以接着后面调用then方法
    第一个打印的结果为上一个then方法传递的resolve，
    第二个打印的结果为undefined,因为上一个then方法没有调用resolve或者reject更改PromiseResult,所以为undefined,
		但是上一个Promise的状态还是resolve
  */
   
  new Promise((reslove, reject) => {
      reslove(1);
    }).then(res => {
        console.log(res); // 1
        return 2;
    }).then(res => {
        console.log(res); // 2
    }).then(res => {
        console.log(res); // undefined;
    });   

new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve('foo');
      }, 300);
    }).then()
      .then()
      .then()
      .then(res => {
        console.log(res); // foo
      });
```

## Promise异常穿透

**当使用promise的then链式调用时，可以在最后指定失败的回调**

```js
//当 .then() 中缺少能够返回 promise 对象的函数时，链式调用就直接继续进行下一环操作。因此，链式调用可以在最后一个 .catch() 之前把所有的处理已拒绝状态的回调函数都省略掉。
const p = new Promise((resolve, reject) => {
    reject('REEOR')
  }).then(() => {
    console.log('111');
  }).then(() => {
    console.log('222');
  }).catch((value) => {
    console.log(value);
  })
  //结果只为ERROR
```

## Promise中断链式调用

**当使用promise的 then链式调用时，在中间中断，不再调用后面的回调函数 办法:在回调函数中返回一个pendding状态的 promise对象**

```js
  new Promise((resolve, reject) => {
    resolve('OK')
  }).then((value) => {
    console.log(value);
    return new Promise((resolve, reject) => { });
    //返回一个新的Promise状态为pending；就不会调用下面的then方法了，因为调用then方法状态必须改变
  }).then(() => {
    console.log(111);
  }).then(() => {
    console.log(222);
  }).then(() => {
    console.log(333);
  })
```

## Promise在方法中的调用

```js
// 当在Promise.then中return的只是这个promise的PromiseResult，不并能当做当前函数的Promise，相当于一个函数里面调用了另一个函数，里面的函数返回值并不是外层函数的返回值
function test() {
  new Promise((res, rej) => {
    res('aaa')
  }).then(res => {
    return res + 'bbb'
  }).then(res => {
    return res + 'ccc'
  })
}

console.log('res :', test()); // undefined

//---------------------------------//
/**
	return的结果都是以Promise的then最后一次调用为准的
	若最后一次没有return，则返回的结果为undefined。
*/
function test() {
  return new Promise((res, rej) => {
    res('aaa')
  }).then(res => {
    return res + 'bbb'
  }).then(res => {
    return res + 'ccc'
  })
}

console.log('res :', test());
/**
	[[Prototype]]: Promise
	[[PromiseState]]: "fulfilled"
	[[PromiseResult]]: "aaabbbccc"
*/

function test() {
  return new Promise((res, rej) => {
    res('aaa')
  }).then(res => {
    return res + 'bbb'
  }).then(res => {
    return 'ccc'
  })
}

console.log('res :', test());
/**
	结果：
	[[Prototype]]: Promise
	[[PromiseState]]: "fulfilled"
	[[PromiseResult]]: "ccc"
*/

function test() {
  return new Promise((res, rej) => {
    res('aaa')
  }).then(res => {
    return res + 'bbb'
  }).then(res => {
  })
}

console.log('res :', test());
/**
	结果：
	[[Prototype]]: Promise
	[[PromiseState]]: "fulfilled"
	[[PromiseResult]]: "undefined"
*/
```

